<?php 
/**
 * Functionally, this drupal module provides an Active Record style way of accessing drupal objects.
 * It also provides more complicated functionality, as versionable custom objects, and a search-builder.
 * @author Matthew Baggett <matthew@baggett.me>
 */

function active_record_permission() {
	return array(
		"version control"			=> array('title' => "Have Version Control"),
	);
}

function active_record_has_version_permission(){
	return active_record_check_permission('version control');
}

function active_record_check_permission($permission){
	global $user;
	return user_access($permission, $user);
}
