<?php


// Load core Models
require_once("models/role.inc");
require_once("models/role_permission.inc");
require_once("models/user_role.inc");
require_once("models/user.inc");

function active_record_permission()
{
    return array(
        "version control" => array('title' => t("Have Version Control")),
        "view queries" => array('title' => t("View Queries"))
    );
}

function active_record_has_version_permission()
{
    return active_record_check_permission('version control');
}

function active_record_check_permission($permission)
{
    global $user;
    return user_access($permission, $user);
}

function active_record_block_view($delta = '') {
    $block = array();
    switch ($delta) {
        case 'query-log':
            $block['subject'] = t('Active Record Query Log');
            $block['content'] = query_log::render();
            return $block;
    }
}

function active_record_block_info() {
    $blocks['query-log'] = array(
        'info' => t('Active Record Query Log'),
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocks;
}
